### ISSUE TITLE
Thanksgiving HW (jmoon)

### ISSUE THREAD

**Issue by mooniker** [ga-dc/thanksgiving-homework#11]
# Part 1

Completeness: 5/5
Comfort: 4/5

I did all three for the extra practice and found them all kinda similar. By the third one (infinite-giphy) I switched over to using the $getJSON instead of $.ajax and I gather it's shorthand but I was a little confused about where to put the promises (done, fail, always). I gather that it takes a done-like function as an argument (success).

https://github.com/mooniker/infinite-giphy
https://github.com/mooniker/spotify-me
https://github.com/mooniker/movie-browser
# Part 2
- How is Express related to the MEAN stack?

Express is kinda like the Rails component of a Ruby on Rails web stack, and handles the MVC and business logic of the app.
- How does Express differ from a framework like Sinatra?

Express is built on Javascript/Node. Otherwise it seems really similar so far.
- How would you choose one over the other when starting a new project?

I would look for the platform that does the most you want to do out of the box and has less unnecessary stuff. Also, comfort level with Javascript and/or Ruby is probably a big deal. Not yet particularly clear on specific strengths Express has over Sinatra or vice versa
- What big picture questions do you have?

Besides when to use Express vs Sinatra/Rails, I’ve always been really confused by callbacks and coding for async behavior of the functions. Seems like a big shift from the way I normally code things.

**Comment by andrewsunglaekim** [comment]
yep you just chain promises right after the parens of the `$.getJSON`. I think i would use express/sinatra if I knew i was creating an app with a simple domain `< 2` models. Anything with more complex associations and problem domain, Rails would be my bet. Async code provides a lot of advantages when it comes to order of execution. Makes handling it all a little bit more manageable i feel like. We want something to happen when something else happens can bring alot of power to the table. With that though, can bring a lot of pitfalls. When you get used to those, the shift won't seem as large.
