### ISSUE TITLE
Part Two [Thanksgiving Homework]

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-dc/thanksgiving-homework#13]
Comfort - 5
Completeness - 5
1. MEAN Stack - Mongo.db, Express, Angular, NodeJS
2. Sinatra is used as a Ruby backend, & express is used as a javascript backend
3. If you want to work exclusively in the Javascript code, you can use the MEAN stack. If you want to start in Ruby code, you can use that stack.
4. Rails seems like a easier choice to use, due to the convention over config. mindset it has.

**Comment by amaseda** [comment]
:+1:
