### ISSUE TITLE
Daniel Alexander HW

### ISSUE THREAD

**Issue by dan-ator** [ga-dc/thanksgiving-homework#14]
Part 2: Node School
I did not like this tutorial, it seemed like I was supposed to just copy and paste what they wrote and I could not get through it all.  When I did do something wrong I had no idea why or what actually I was supposed to be accomplishing.  I tried setting it up again but to no avail. 

How is Express related to the MEAN stack?  Express is the back-end framework part of the MEAN stack.
How does Express differ from a framework like Sinatra? There seems to be a lot more configurations that need to manually be set up.
How would you choose one over the other when starting a new project? If something needs more customization I guess I would choose Express.
What big picture questions do you have? Not sure I can get into big picture, still more concerned with how express works.  Didn't do too well with ajax or apis either.

Part 1:
https://github.com/dan-ator/spotify-me
comfort: 3.5
completeness: 4

The app mostly works.  There is an error shown in the console of cannot read property name of undefined, but it still compiles the list so not sure why the error or why it is still working anyways.  Otherwise I would like to be able to make it so when you do a new search the old results are removed.

**Comment by adambray** [comment]
Hey Dan,

Your spotify code looks good! I filed a PR to leave a small bit of feedback on it. Other than that, your answers to the questions look good. As for your comment regarding the big picture, feel free to grab me this week and we can talk about it.

-Adam
