### ISSUE TITLE
Ly - Thanksgiving HW

### ISSUE THREAD

**Issue by Ly900** [ga-dc/thanksgiving-homework#16]
### Movie Browser

[Link to my Movie Browser Repo](https://github.com/Ly900/Thanksgiving-Homework-Movie-Browser)

**Completeness:** 5

**Comfort:** 4 (Not completely comfortable with passing variables from function to function and not familiar with the getJSON syntax from the solution.) 

I really enjoyed working on this activity.
## Part 2

**1. How is Express related to the MEAN stack?** 

Express is the "E" in the MEAN stack. It is the back-end framework. It is to Node.js what Sinatra is to Ruby. 

**2. How does Express differ from a framework like Sinatra?**

Express uses Node.js and Javascript while Sinatra uses Ruby.

**3. How would you choose one over the other when starting a new project?**

I'm not really sure but initially I would choose the language I prefer.

**4. What big picture questions do you have?**

I am not completely sure how Express, Node, Javascript, and everything fit together. For example, are we writing code in Node.js or Javascript? What is the structure of Node.js and how is it different from JS? I am still confused about the roles of nmp, nodemon, Jade, HBS, etc. 

I was not able to finish the codeschool exercises because the hints were not enough to help me through. I kept getting an error that said they couldn't find jade and couldn't get past that. The tutorial is not in-depth enough to serve as a tutorial. I think another one should be provided in lieu of or in addition to this one in the future. 

I think more repetition with Express the way we did it with Rails would be really helpful to solidify for us how everything works and fit.

**Comment by andrewsunglaekim** [comment]
NodeJS is just a run time environment for javascript. Before 2009, javascript was only used on the client side. People liked javascript so much that they wanted to use it as a scripting language to communicate with servers. Enter NodeJS. `npm` is just a package manager think of it like bundler in rails. Jade and handlebars are just templating engines. And nodemon is a node package that refreshes the server in case file changes are made.

**Comment by Ly900** [comment]
Things are getting clearer. Thanks!
