### ISSUE TITLE
Chase HW part 2

### ISSUE THREAD

**Issue by cpgruber** [ga-dc/thanksgiving-homework#17]
1) Express is the framework that acts as the switchboard in the MEAN stack, connecting routes to databases and APIs, managing requests and returning responses to HTTP methods.

2) Express is a javascript framework, so it can more easily be integrated with AJAX to create single page web applications, whereas in Sinatra you often need to refresh or render a page between calls to the database. 

3) I would consider the purpose of my application first and foremost. If a clean user experience is desired, then I would tend toward Express so I could accomplish more with fewer page loads and refreshs. 

4) I didn't get a whole lot from ExpressWorks, I found it frustrating and not all that helpful. I'm hoping that I'll come around to node and express though, as I do find javascript more enjoyable to write than ruby. Excited to put the rest of the MEAN stack together.

**Comment by jshawl** [comment]
:+1: Angular is only a few short weeks away!
