### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by jordanbrauner** [ga-dc/thanksgiving-homework#19]
Completeness: 2
Comfort: 1

Comments: Not a fan of Expressworks at all. I found it and the instructions for each exercise to be obscure and it required me to put more time into it than I should have in order to understand it. This would be fine if it was a bonus exercise but as homework I think it shows a lack of respect for our time.

How is Express related to the MEAN stack?
Express is a framework built on top of Node, and allows us to run Javascript locally. It's the "E" of MEAN.

How does Express differ from a framework like Sinatra?
Express is a framework for Javascript while Sinatra uses Ruby.

How would you choose one over the other when starting a new project?
Not yet sure other than personal preference (Ruby vs. Javascript)

What big picture questions do you have?
None yet.

**Comment by amaseda** [comment]
:+1:
