### ISSUE TITLE
ThomasS-Parts 1&2

### ISSUE THREAD

**Issue by solowt** [ga-dc/thanksgiving-homework#2]
https://github.com/solowt/infinite-giphy
comfort: 4 completeness: 5

I think there are probably better ways to do this (for example, making 1 call for every result and then going through the results 10 at a time). I might take a look at that later in the week.

edit- reduced code a little and removed unneeded global variables

**Comment by solowt** [comment]
I wanted more practice so I did the movie one too: https://github.com/solowt/movie-browser

Will add another comment when I get through the express tutorial.

**Comment by solowt** [comment]
I feel like I understand node and express on a high level, but I definitely need some more practice before it sinks in.  I didn't feel especially comfortable doing the expressworks tutorial.  I understood what each line of code was doing, more or less, but I relied on hints/google to solve each problem.  

I also don't understand npm nearly as well I understood gemfile/bundle install.  I've run into some issues with global npm modules versus local ones as well as issues with permissions (that I solved using sudo commands).

How is Express related to the MEAN stack?

Express is the 'E' in MEAN, it's a framework for writing web apps using javascript.  It's similar to sinatra in terms of syntax, although sinatra is a ruby framework.

How does Express differ from a framework like Sinatra?

The most obvious difference is that they use different languages, express uses js and sinatra uses ruby.  Aside from this, express can run in the terminal whereas we always used a browser with sinatra.  I think express is probably better at handling asynchronous calls because it's written in js although that's just a hunch. 

The two seem fairly similar in terms of syntax, although express requires more explicit linking of files and dependencies. 

How would you choose one over the other when starting a new project?

I think if I was planning on using lots of asynchronous tasks/functionality, I would prefer express.  I don't really have a good answer to this since I don't remember much about sinatra, other than it being a lightweight alternative to rails with much less "magic."

What big picture questions do you have?

I have some questions about how express would actually be used in combination with a DB and angular (also don't know what angular is) but I'm sure we'll get to those things in time.

**Comment by nolds9** [comment]
:+1: Great job tackling both exercises, we will get a much better picture of the how the pieces in the MEAN stack fit together in the next few weeks, but is still worthwhile to study the parts in isolation to compare them to other alternatives because there are different tech stacks out there!
