### ISSUE TITLE
Brendan Mahoney - Part Two

### ISSUE THREAD

**Issue by BMahoney08** [ga-dc/thanksgiving-homework#20]
1 - How is Express related to the MEAN stack?

Express is a web application framework in the MEAN stack that handles the server side requests, e.g., a "GET" request for the index page of a web application, and then rendering the appropriate view on the client side.

2 - How does Express differ from a framework like Sinatra?

Express requires more manual configuration than Sinatra. Similar to the differences in JS and Ruby, much less is implicit in Express than Sinatra.

3 - How would you choose one over the other?

For simpler web applications that only offer CRUD capabilities, I would prefer Sinatra. However the manual configuration required in Express works well with more complex web applications.

4 - What big picture questions do you have?

 What are some of the more interesting Node packages available?

**Comment by RobertAKARobin** [comment]
Great answers!

Hmm. Interesting Node packages... I haven't used very many, to be honest. Beyond the scope of what we're covering in this class, if I do discover something cool, I'll probably incorporate it into http://github.com/robertakarobin/inap-node
