### ISSUE TITLE
Part Two Thanksgiving HW

### ISSUE THREAD

**Issue by ghost** [ga-dc/thanksgiving-homework#21]
1.) Express is the E in the MEAN stack. It is a very lightweight, sinatra-inspired web-application backend framework. It is the most naturally fitting node.js server. It connect backend DB (mongo) with front-end js framework (angular). Written on node.js npm libraries.

2.) Express was built to be similar to sinatra. Where sinatra uses ruby, express uses node.js.

3.) Currently, comfort level/context would be my primary deciding factor. They are very similar and are capable of producing similar user experiences. Unless I was intentionally trying to gain experience in a specific language, I would use the one I felt more comfortable with and able to produce the best product. Assuming sinatra is capable of asynchronous data requests similar to ajax. 

4.) I felt like I spent a lot of time learning expressworks and didn't gain a lot about Express. I ended up using the solution a lot just to figure out what they were asking.

**Comment by jshawl** [comment]
:+1: This is helpful feedback re: expressworks. Thanks!
