### ISSUE TITLE
Thanksgiving HW, Part Two

### ISSUE THREAD

**Issue by schersh** [ga-dc/thanksgiving-homework#22]
How is Express related to the MEAN stack?
Express is the back-end web framework used within the MEAN stack of MongoDB, Express, Angular, and Node.js. 

How does Express differ from a framework like Sinatra?
Express is event-driven, and since it has asynchronous functionality it allows your program to do many operations simultaneously. The two frameworks both have supporting libraries/gems that can support your program (using npm or bundler installers), but express seems to be more lightweight overall, which I think means that it has produces more efficient runtimes. 

How would you choose one over the other when starting a new project?
I think it would depend which code base you are working in. If you are working on a Ruby app, then Sinatra might be a better fit in terms of configuration. The advantage of using Express as part of the MEAN stack is that you are able to use Javascript to serve both your front- and back-end frameworks. Express might be a better choice if you have a project that requires asynchronous I/O, whereas Sinatra seems to have more support built-in for database tasks. 

What big picture questions do you have?
How do Express and Sinatra compare to Go?

**Comment by jshawl** [comment]
> How do Express and Sinatra compare to Go?

Express and Sinatra are web frameworks. Go is a programming language. There are web frameworks for Go like Revel and Martini.

Sinatra is to ruby as
Express is to javascript as
Martini is to go
