### ISSUE TITLE
Part Two - Thanksgiving Homework

### ISSUE THREAD

**Issue by roshanad** [ga-dc/thanksgiving-homework#23]
How is Express related to the MEAN stack?
Express is back-end web framework that handles application routing. It’s the “E” of MEAN. 

How does Express differ from a framework like Sinatra?
Express is JavaScript framework while Sinatra is for ruby. 

How would you choose one over the other when starting a new project?
For simple web application that would just require CRUD capabilities, I would choose Sinatra and for more complex web application I would choose Express.

What big picture questions do you have?
Don’t have any questions yet.

**Comment by ebirving** [comment]
:+1:
