### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by ghost** [ga-dc/thanksgiving-homework#26]
A brief reflection on your opinion and understanding of node and express.
Hmmm.  Node is used to write applications in javascript on the server; up until now we've written javascript apps on the client side (browser).  Express is a framework written on node that makes it easier to write these applications.  

How is Express related to the MEAN stack?
Express is a web framework that works on language node.js.  It's used to write apps on node (N)  that query the db (M - Mongo) and interface with Angular (A) on the client side.  

Is it fair to think of Express as a bridge, conduit or connector?

How does Express differ from a framework like Sinatra?
Sinatra seems cleaner, need to write less code.  But Express lets me write in javascript, so being familiar with javascript allows me to write apps and functions on the client and server sides.  I think Express will "scale up" better to support more complex applications.

How would you choose one over the other when starting a new project?
Familiarity with javascript; scope and complexity of the functionality of the project I'm working on.

What big picture questions do you have?
Trying so hard to get these exercises to work and learn the syntax that it's hard for me to step back and look at the high level/big picture.  I have my nose two inches from the screen; need to breathe as I get more comfortable with the syntax so I can understand how the pieces fit and work together.

**Comment by jshawl** [comment]
> Is it fair to think of Express as a bridge, conduit or connector?

Sure! It's what connects the client to the server. It's also the interface between the user and database transactions.

> it's hard for me to step back and look at the high level/big picture

I recommend trying to solve a problem with pen and paper. I know it's a little weird, but can help you 
think of how to solve a problem without worrying about syntax errors. This will help with the big picture view.
