### ISSUE TITLE
Part One

### ISSUE THREAD

**Issue by jacohen10** [ga-dc/thanksgiving-homework#27]
https://github.com/jacohen10/movie_browser
Comfort: 4
Completeness: 5
Took me a bit longer than I was hoping considering it was the easiest of the 3 options, but I'm going to try a harder one before it gets too late and hopefully it'll be easier now that I've done it once

https://github.com/jacohen10/infinite-giphy
was able to do this one in an hour during lunch, so was really happy it went a lot more smoothly. I also did the movie_browser from scratch, so maybe that's why it took so long? Idk

**Comment by amaseda** [comment]
Great job with Movie Browser. I would consider encapsulating the code in your promises into separate functions. Will make your code more readable if you organize that code according to behavior.

**Comment by amaseda** [comment]
Great job with Infinite Giphy as well. If you want to make it truly infinite, you'll want to load the next batch of GIFs in your search results. This is where the `offset` property comes in. Take a look at how it's used in the [Giphy API](https://github.com/giphy/GiphyAPI). The [Spotify API](https://developer.spotify.com/web-api/search-item/) also makes use of a similar property.

**Comment by amaseda** [comment]
:+1:
