### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by jacohen10** [ga-dc/thanksgiving-homework#28]
Was pretty frustrated with this tutorial. I don't think it's set up in a way that's conducive to learning the material. There aren't any real explanations and it does key parts for you which I also didn't like. I hope we don't get something like this again. After a certain point I just ended up looking at the question, trying to do as much as I could and then looked at the solution, which unfortunately still didn't help me understand it any better.

I really like what node and express allow you to do and I understand it on a very high level, but I'll need a lot more practice with it and further instruction on specifics before I'll feel close to comfortable with it.

**How is Express related to the MEAN stack?**
Express is the E in MEAN. It's a web app framework built on top of node that uses Javascript like Sinatra uses Ruby

**How does Express differ from a framework like Sinatra?**
Besides using Javascript instead of Ruby, the main difference is Express allows you to make asynchronous calls as opposed to just synchronous calls(requests?). 

**How would you choose one over the other when starting a new project?**
I would use Express if my project was heavily focused on UI otherwise I'd use Sinatra at this point until I was more familiar with Express

**What big picture questions do you have?**
After we learned Sinatra we ended up just using rails. Will we end up doing the same thing with Angular?
I'm interested in seeing/learning how the whole MEAN stack will come together

**Comment by amaseda** [comment]
:+1: 

And thanks for the input on ExpressWorks. Will keep that in mind for future assignments/cohorts!
