### ISSUE TITLE
Rachel - Part One

### ISSUE THREAD

**Issue by ddayporter** [ga-dc/thanksgiving-homework#29]
Comfort: 4
Completeness: 4

My solution: https://github.com/ddayporter/spotify-me/tree/rachel-solution

It meets the basic requirements but haven't finished the pagination feature. I found a jquery plugin to do pagination (http://www.jqueryrain.com/?piHSAiMw), is it simpler than that?

**Comment by mattscilipoti** [comment]
Simpler Pagination?  Your gut is right.  That is a rather complicated pagination.  What do you need from your pagination?  When I try to break it down to the simplest needs, I see 3 dependencies: current_page, number of items per page, and a way to request the items for this page.

**Comment by mattscilipoti** [comment]
It can be as simple as this: https://github.com/ga-dc/infinite-giphy/blob/solution/js/giphy.js
