### ISSUE TITLE
Kain: Thanksgiving HW Parts 1 & 2

### ISSUE THREAD

**Issue by elisekain** [ga-dc/thanksgiving-homework#3]
Completeness: 5
Comfort Level: 4

Infinite Giphy Repo: https://github.com/elisekain/infinite-giphy

Express Tutorial Questions:
How is Express related to the MEAN stack?
Express is a back-end framework built on top of Node.js that makes it easier to create/manage routes and interact with API's (communicating in JSON and AJAX calls). Receives each type of http request at each specified route and sends back a response.

How does Express differ from a framework like Sinatra?
Other than the very obvious (they are written for different languages...JS for Express and Ruby for Sinatra), Express seems better suited and developed for asynchronous operations (lots of AJAX calls and JSON data). Online forums seems to indicate that Express is faster than Sinatra. 

How would you choose one over the other when starting a new project?
From researching online and my very minimal introductions to both frameworks, I feel like Express is set up better for heavy interaction with API's where the developer wishes to have the application response asynchronously. 

What big picture questions do you have?
I don't have a great grasp of how the pieces within the MEAN stack interact with each other. Looking forward to putting all the pieces together.

**Comment by jsm13** [comment]
:+1: Awesome job with this! Absolutely right here. How has this week been in understanding the ME(hand rolled MV\* front-end)N stack?
