### ISSUE TITLE
Chris Kibble HW

### ISSUE THREAD

**Issue by ckib16** [ga-dc/thanksgiving-homework#30]
# Part 1

Wow. I am pretty lost. I'm going to have to go re-do the Express Lesson from last Tuesday before tackling this.
# Part 2

> How is Express related to the MEAN stack?  

Express is the E in "MEAN". MongoDB, Express, Angular, Node. Essentially, Express is the back-end framework, similar to Sinatra. It's also somewhat like Rails, but much "lighter" and more free-form.

> How does Express differ from a framework like Sinatra?

It's similar to Sinatra in that it is "lighter" and more bare-bones. It's different in that it doesn't have a lot of things ready to go "out of the box"

> How would you choose one over the other when starting a new project?

I would personally choose Sinatra because I am more familiar. But if the app is going to be JS heavy due to front-end requirements etc., it may make sense to do the whole app in JS.

> What big picture questions do you have?

I am still in Ruby/Rails mode, and having a hard time context switching between JS and Ruby. I guess my question is - does this "context switching" cost ever go down? Or is it still pretty significant limitation to jump between the two languages?

**Comment by RobertAKARobin** [comment]
It's just like switching between foreign languages. I haven't taken German in years and still find myself slipping words in when I try to speak French. The more you do it the more fluid it'll be, but even then it'll probably never quite go away.
