### ISSUE TITLE
B Boy Thanksgiving HW

### ISSUE THREAD

**Issue by brittonwalker** [ga-dc/thanksgiving-homework#33]
Part 1
completeness: 4.5
comfort: 4

https://github.com/brittonwalker/movie-browser
https://github.com/brittonwalker/spotify-me

I completed two, was really shooting for three but ran out of time. I didn't get the pagination on spotify and would like to know how. I also used .getJSON instead of AJAX, are we still supposed to use .fail/.always or is there another thing like .success? My apps are not set up to display for failure, which I would have liked to account for. 

Part 2

I absolutely hated that express tutorial, it seemed very unclear and that it wasn't helping at all so I watched lynda.com tutorials instead. 

Node allows you to run javascript on a server. I works asynchronously so a benefit is there is no waiting time and can handle a lot of connections simultaneously. Express is a framework that gives node more robust capability for using node to build websites and uses an MVC pattern. 
1. The MEAN stack is a full-stack collection of Javascript technologies, from front to back. 
2. Express is to JS what Sinatra is to Ruby, or so it seems. Express appears to be faster. The ruby community seems to have more elegant documentation.
3. To choose one over the other, I would look at my project and then research to no end which framework would fit my needs better.
4. It appears that node is more ideal for building single page apps and programs that users interact with one another i.e., games/chat. Since we began this course, I have heard a lot of different people in the dev community choose Rails or Node as if they were two sides of 'the force'. Does this mean that these people tend to take on different kinds of projects? I feel like since javascript is one of the three main languages used in the browser, it is more sensical to focus on becoming a highly skilled javascript developer before anything else. It appears to be fast because of the asynchronicity, however, I am not certain and would like to know more about performance.

**Comment by nolds9** [comment]
:+1: Awesome job tackling 2 exercises! Sorry you felt that express tutorial was not worthwhile, but glad you still took the initiative to learn more. We will get a much better picture of the how the pieces in the MEAN stack fit together in the next few weeks, but is still worthwhile to study the parts in isolation to compare them to other alternatives because there are different tech stacks out there!
