### ISSUE TITLE
Starr's Thanksgiving HW

### ISSUE THREAD

**Issue by starrchen** [ga-dc/thanksgiving-homework#35]
Hope you had a great holiday weekend!
## Part 1 - [Spotify.me](https://github.com/starrchen/spotify-me)

Repo URL (also above): https://github.com/starrchen/spotify-me

Completeness: 5
Comfort: 4

Definitely see a need to DRY this code, so I'll work out that soon. This was a lot of reviewing things that I did not remember and/or barely absorbed last week, so I struggled to get it working. Once I got the artist search working, however, it came together pretty nicely, and I _think_ I can figure out how to refactor this to make the code look nicer. Hopefully. Fingers crossed. Maybe.

Will try to do the bonuses after DRYing the code.
## Part 2

Completeness: 2?
Comfort: 2

Um, okay, this tutorial is really confusing I don't even understand how to go through it????? It has stumped me and the developer who tried to help me what is going on? Honestly, there were times when it made me question what I learned about Express.js already and that scared me a lot. I spent exponentially more time trying to figure out how to make the tutorial go than actually learning Express with the tutorial. The "cool" factor of doing a tutorial within the terminal was quickly overridden by how cumbersome it was. 

BUT after working through our lesson plan and a guide that someone showed me, I think I can still answer the questions: 
#### How is Express related to the MEAN stack?

MEAN stands for:
- MongoDB
- Express -- bingo, that's what we're looking for here!
- AngularJS
- Node.js

Express is the framework in the stack.
#### How does Express differ from a framework like Sinatra?

Express is a framework that operates on JavaScript while Sinatra is a framework on Ruby. Express also seems to be faster (hence the name?) than Sinatra.
#### How would you choose one over the other when starting a new project?

Sinatra seems to be a good fit when you are building a smaller web application (although some folks online say that Sinatra can handle bigger applications if you know your way around). 

But also, it seems to often boil down to what you're more familiar/comfortable with: Ruby or JavaScript. That's probably more of a deciding factor at this point for us (and for other developers too?)
#### What big picture questions do you have?

I still feel like I don't have a good grasp on when you would use one framework or the other besides language comfort? Or is that really what it comes down to??? That can't be it, can it? It definitely seemed like folks chose one over the other depending on how comfortable they were working with either on the back end. 

And how we will be integrating everything we learned last week? For example, I was wondering if maybe the asynchronous requests may have played a role with choosing Express but on second thought, you can have concurrent requests in Ruby as well, right? But I feel like this may have been one of the actual determining factors, I just couldn't quite understand what the difference was.

I think a really deep review of the material from last week would benefit a lot. Like a **_lot_**?

---

I'll try to finish this tutorial still, but if I don't, here are my responses. I took a peek at some of the other HW submissions to see if there was someone who SUPER got it that I could ask, but it seems like this was an unpopular tutorial.

**Comment by amaseda** [comment]
**Spotify.me**
Looks great. Nice use of a ternary to implement search functionality! Let me know if you have any questions about the assignment and how to go on refactoring / implementing bonuses.

**Comment by amaseda** [comment]
**Part 2**
Thanks for your comments on ExpressWorks. Will take that into account for future assignments and cohorts! And I mentioned this in class but on Friday morning we'll be having a Big Picture Review which will be a great opportunity to bring up the questions you mentioned under `What big picture questions do you have?`. Happy to talk about these in-person too.

**Comment by amaseda** [comment]
:+1:
