### ISSUE TITLE
Alexis_ThanksgivingHW_PartOne

### ISSUE THREAD

**Issue by ajohnson052** [ga-dc/thanksgiving-homework#36]
https://github.com/ajohnson052/spotify-me

Completeness: 5
Comfort: 3

I wasn't able to finish the bonus because I was having trouble figuring out how to enter 'offset' and 'limit' parameters to the Spotify API when working with a query.

**Comment by jsm13** [comment]
:+1: I think it had to do with [authorization](https://developer.spotify.com/web-api/authorization-guide/) and that anyone can make a general request but a key is needed for more specific requests. Great job!
