### ISSUE TITLE
Part One - Tory Burgett

### ISSUE THREAD

**Issue by toryburgett** [ga-dc/thanksgiving-homework#37]
Movie Browser: https://github.com/toryburgett/movie-browser
^ Completeness: 5/5, understanding: 4/5
Infinite Giphy: https://github.com/toryburgett/infinite-giphy
^ Completeness: 4/5, understanding: 3/5 -- (didn't finish the project, no scrolling, better name = finite giphy)

**Comment by amaseda** [comment]
:+1: I'll leave code comments via a PR to your hw repos.

**Comment by amaseda** [comment]
Great job with Movie Browser. Should you decide to revisit the assignment, I encourage you think about ways you can refactor your code to make it more readable and perhaps consolidate some of the behavior in there into their own functions. Let me know if you have any lingering questions about it, but looks like you've got a good grasp on making and playing around with client-side API calls!

**Comment by amaseda** [comment]
Great job with Infinite Giphy too! One step to getting where you want to be is removing that `$("#searchArea").remove()` from Line 33. That way, you're not replacing one batch of GIFs with another every time you search (i.e., it'll be almost infinite!). But you will need to make sure that each of batch of GIFs is rendered properly on the page.

**Comment by amaseda** [comment]
:+1:
