### ISSUE TITLE
Alex's Solution - Part 1

### ISSUE THREAD

**Issue by ascreven** [ga-dc/thanksgiving-homework#38]
Comfort - 4
Completeness - 5

I did all of the basic requirements but got caught up for a long time on simple issues (getting and installing a key... it was given to us & preventDefault)

That said, I definitely feel more comfortable with this that the expressworks tutorial. John underestimated though when he said that the homework should only take a total of 6 hours.

**Comment by mattscilipoti** [comment]
Thanks for the feedback.
