### ISSUE TITLE
Rebecca HW Part Two

### ISSUE THREAD

**Issue by rebeccaestes** [ga-dc/thanksgiving-homework#40]
This tutorial was really frustrating for me. I passed some levels even though my code was not actually working, and failed others even though I was generating the solution (just not in the format they wanted it, I guess). Looking at the solutions didn't help much, because they only offered the main program.js file, so if your error was in another file you're just out of luck. And I don't think what I did in the tutorial helped me answer the questions for this homework either.

<b>How is Express related to the MEAN stack?</b>
The MEAN stack is comprised of Mongo, Express, Angular, and Node. Express provides the back-end web framework - it basically is JavaScript's version of Ruby's Sinatra. It listens for incoming requests, finds the corresponding route, and then provides the responses given there.

<b>How does Express differ from a framework like Sinatra?</b>
Express uses Javascript and Sinatra uses Ruby. According to my google research Express is either better at asynchronicity than Sinatra, or it has asynchronicity whereas Sinatra generally doesn't. I wasn't clear on this.

<b>How would you choose one over the other when starting a new project?</b>
If we're comparing Express to regular rail-less Ruby*, I would probably use Express simply because I feel more comfortable in Javascript ... after getting a better tutorial/more practice with Express, at least. Beyond a personal preference, I guess if I were making a lot of calls to the server, I would use Express so that I could take advantage of its asynchronicity. I did google research here too and couldn't really find a list of the pros and cons of each.

<b>What big picture questions do you have?</b>
What is the purpose of using .jade and .styl files instead of regular HTML and CSS?

I think when we were learning the steps to putting together a Rails app, I was concentrating on following along so much that it took me until the end of my project to realize that the controllers in Rails projects were literally lists of functions, and that the models were defining the classes for which we were creating instances. I wish I had figured that out sooner because everything made a LOT more sense after that - I actually understood the reasoning behind what I was doing, instead of just following the instructions I had written down and thinking it was just a weird set of steps that I had to learn. 

Anyway, I think I'll have better luck noticing these things in the MEAN stack than I did with Rails just because I'm a lot more familiar with Javascript right now than I was with Ruby when we started to build back-end apps there. E.g. looking at this line of Express code: 

`app.get('/message/:id', function(req, res) { whatever })`

It's basically applying the method get to the object app, and passing as parameters the URL and the function, right? As a very big picture question, does that mean that somewhere out there there is a definition of the object app, that would list all its methods and properties?

\* Sinatra is used just with Ruby, not Rails, right? I.e. I shouldn't compare the Express exercises to our most recent project. I feel like the node errors were a notch below Rails in terms of helpfulness, but much better than what Sinatra gave.

**Comment by ebirving** [comment]
We would use `.jade` for the same reasons we use Handlebars -- a templating language that allows us to insert values from the back end into the UI. `.styl` is a bit of a different case. It's more like Coffeescript, CSS, or Haml, a simplified syntax for writing an existing language -- totally a developer happiness/preference thing. 

Yes, your breakdown of that `app.get` line is correct!

Yes, yes, and yes to your Sinatra/Ruby/errors/all of the above.
