### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by Cajam** [ga-dc/thanksgiving-homework#42]
How is Express related to the MEAN stack? 
Express is a framework similar to Rails for Ruby.

How does Express differ from a framework like Sinatra?
Express has the node package manager, Sinatra alone doesn't utilize Ruby on Rails gems.

How would you choose one over the other when starting a new project?
I'd use Rails to build a simple website that didn't need complex functionality, and Express to build something that required more customization.

What big picture questions do you have?
How often is node written from scratch instead of just using express?

**Comment by jshawl** [comment]
> How often is node written from scratch instead of just using express?

I would say very rarely. There are alternative frameworks like hapi.js and sails.js and koa.js. Writing an http server from scratch is possible, but requires a bit of wheel reinventing.

:+1:
