### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by matiamin** [ga-dc/thanksgiving-homework#44]
1- How is Express related to the MEAN stack?
MEAN stack is MongoDB (database), Express and Angular (frameworks) and Node.js (a runtime environment for developing server-based web applications. 

2- How does Express differ from a framework like Sinatra?
Express, just like Sinatra, is less opinionated. Unlike Rails, you've a lot of freedom to how you want to structure your application. As for the difference, I think Express is more oriented towards asynchronous operation than Sinatra is. I think.   

3- How would you choose one over the other when starting a new project?
Based on personal preference, I'd use Rails or Sinatra at this point. I haven't had greater exposure to Express and don't feel as comfortable as I do with Rails for instance. 

4 - What big picture questions do you have?
I understand that Express is more flexible in terms of file structure and formatting but that is something that is throwing me off. I think it is just a matter of more practice and getting use to.

**Comment by adambray** [comment]
Hey Mati, nice answers to these questions. I can't find any record of work on Part 1, do you have anything?
