### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by neka-io** [ga-dc/thanksgiving-homework#45]
I started the tutorial but the instructions were often vague and I wasn't sure how to proceed. 

How is Express related to the MEAN stack?
MEAN stack is a framework of technologies that are used together to build web applications. It includes Mongo DB (a non-SQL database), Express (a js web framework), Angular (a front-end js library) and Node (which enables use of js in the backend). 

How does Express differ from a framework like Sinatra?
Express is similar to Sinatra in that it is unopinionated and there are a lot of configurations to be made. Sinatra is a Ruby framework whereas Express is a JavaScript framework that works on Node.js. 

How would you choose one over the other when starting a new project?
Express and Sinatra are both suitable for smaller scale apps or prototyping as they are fast and quick to set up. Since Node.js is new compared to Ruby, there are more gems available to use with Sinatra that might make life easier. The advantage of Express is that the back end and front end are both in one language. 

What big picture questions do you have?
I'd like to better understand MEAN stack in terms of the rMVC model. Also I want to know how Node.js and Ruby are different on the client side and what the implications of that are.

**Comment by jsm13** [comment]
:+1: so the rMVC model we talked about with Rails would all be within Express and Node (models utilizing Mongo(ose)) and less strictly structured than we needed to be in Rails. We're also been using a MV\* structure in our front end JS so we have front end views and models as well as back end views and models.
