### ISSUE TITLE
Alexis_ThanksgivingHW_PartTwo

### ISSUE THREAD

**Issue by ajohnson052** [ga-dc/thanksgiving-homework#46]
Within the MEAN stack, Express.js is a server-side web application framework as opposed to Angular.js which is a client-side framework.

In comparing Sinatra and Express, it seems that Express allows for greater flexibility within the view files. First, it is easy to pass functions to the view. Also, when using jade with Express, I have noticed that variables/functions that have not been passed into the view are ignored rather than erroring out. This allows that a single view be rendered from multiple routes which each pass different information.

I want to learn more about how Express interacts with a database in order to make a better comparison between the two.

**Comment by jsm13** [comment]
:+1: Has this week on Mongo/Mongoose been helpful in understanding how express interacts with a database?
