### ISSUE TITLE
Part One: HW

### ISSUE THREAD

**Issue by KoryJCampbell** [ga-dc/thanksgiving-homework#47]
https://github.com/KoryJCampbell/movie-browser

Comfort : 3
Completeness : 5

Completely forgot how to do this over the break. Lol. Most of it code from the solution branch, but I understand the concepts of what's going on. Will be doing some more review independently.

**Comment by amaseda** [comment]
Let me know if you have any lingering questions about this assignment - happy to help! Knowing how to make AJAX calls is a requirement for Project 3. Sometimes the solution is enough to get a sense of the concepts at play here, but to get a real feel for this you're going to want to get some practice implementing it yourself.

:+1:
