### ISSUE TITLE
kelly's thanksgiving homework 

### ISSUE THREAD

**Issue by kaustly** [ga-dc/thanksgiving-homework#48]
p a r t ONE
https://github.com/kaustly/infinite-giphy
Comfort: 3ish
Completeness: mvp
Comments: I'm very comfortable with the api, but very uncomfortable with JS still. Got lots of help, but feel good about it.

p a r t TWO

That tutorial was awful. I did not finish it. 

How is Express related to the MEAN stack?
Express is the E in MEAN. Express.js is a server-side web application framework as opposed to Angular.js which is a client-side framework.

How does Express differ from a framework like Sinatra?
Sinatra is a Ruby framework. Express is a JavaScript framework.

How would you choose one over the other when starting a new project?
From what I've read it sounds like Express can handle bigger applications much faster; so, I'd probably use for big projects and Sinatra for smaller ones. (This, of course, assumes I know Express.js which I don't...yet.)

What big picture questions do you have?
Can we go over when it's better to use what languages? Maybe talk about where you find them most often in the wild?

**Comment by adambray** [comment]
Hey Kelly,

Your code for part one looks good, but you mentioned getting help with it... that's ok, but do let me know if there are things you want to go over specifically.

Re your question about when to use which languages... the honest answer is most of the time, it doesn't matter, and what you use would be dictated by a) what you're most comfortable with, or b) what your team is already using. 

The main advantages of JS/Express are that the code runs very fast, and thus scales well to 1000s and 100,000s of users (and more), with few servers.

The main advantages of ruby are: easier to read / write code, better documentation (most of the time),, and more gems / libraries, at the cost of our code running slower.

-Adam
