### ISSUE TITLE
Alice Frumin Part 2

### ISSUE THREAD

**Issue by alifrumin** [ga-dc/thanksgiving-homework#49]
How is Express related to the MEAN stack?
Express is the E in MEAN. It is a node.js web application framework.

How does Express differ from a framework like Sinatra?
Sinatra is built for ruby and Express is built for Javascript.

How would you choose one over the other when starting a new project?
Depending on what language you want to use and how big of an app you want to build. 

What big picture questions do you have?
Looking forward to exploring more. Would like to experiment with the Mongo DB(database) and Angular

**Comment by ebirving** [comment]
:+1:
