### ISSUE TITLE
Armani's Thanksgiving HW

### ISSUE THREAD

**Issue by ArmaniH** [ga-dc/thanksgiving-homework#54]
<b>Part 1:</b>
2/5 on comfortableness
3.5 on completeness, showing movie-select is wonky
https://github.com/ArmaniH/movie-browser

<b>Part 2:</b>
- How is Express related to the MEAN stack?
  Express provides back-end framework. 
- How does Express differ from a framework like Sinatra?
  Besides Express working with JS and Sinatra with Ruby, Express is event driven as opposed to thread driven. 
- How would you choose one over the other when starting a new project?
  Sinatra is great for lighter/simpler programs, as Ruby is simpler to code in and as a wealth of useful Gems. Express, relying on JS requires more upfront work, but can be mor eversatile for larger projects.
- What big picture questions do you have?
  I guess just wondering more about the power of Express and what exact types of applications would be better to use Express for.

**Comment by jshawl** [comment]
> what exact types of applications would be better to use Express

Express is my go-to framework If there's a node module or two I want to use. For example, I might want to build a chat application that requires real-time connections (web sockets). This is possible in a ruby environment, but node is the standard here

Also check out http://expressjs.com/en/resources/applications.html

**Comment by jshawl** [comment]
Would you like to find a time tomorrow or Monday to pair on going over the solution for this exercise? https://github.com/ga-dc/movie-browser/compare/ga-dc:a80d014...ArmaniH:5063cdd

**Comment by ArmaniH** [comment]
I think Monday afternoon, 2 or 2:30 would be great.

**Comment by jshawl** [comment]
Ok great! Got you in the calendar for Monday at 2pm.
