### ISSUE TITLE
Tyler Crosse - Thanksgiving HW

### ISSUE THREAD

**Issue by tylercrosse** [ga-dc/thanksgiving-homework#55]
// Part 1
 Comfort 2.5/5
Completeness 2/5

I was struggling with this and time boxed it so I could focus on resting over the break. I've got some time scheduled to revisit it this evening. The solution used a lot of syntax we didn't cover so I'd like to figure work through exactly what is going on there. Particularly the stuff with offset and how it relates to the giphy API.

https://github.com/tylercrosse/infinite-giphy

// Part 2

`How is Express related to the MEAN stack?`

MongoDB, Express, Angular, & Node. Express works with Node to function as the backend of the MEAN stack.

`How does Express differ from a framework like Sinatra?`

They are both lightweight backend systems, express relies on JS and Sinatra uses Ruby. Both can easily incorporate 3rd party code resources using NPM with Express and Ruby Gem's with Sinatra.

`How would you choose one over the other when starting a new project?`

I'm still more comfortable with Sinatra than I am with Express so that's the biggest factor for me right now. If I had enough time that I could learn Express better while completing a project I would opt for that, otherwise with a short deadline, I would stick to what I know with Sinatra.

`What big picture questions do you have?`

I'm excited to learn more about Mongo DB and Angular and how they work with Node and Express.

**Comment by amaseda** [comment]
:+1:

Left some comments on Infinite Giphy via a PR: https://github.com/tylercrosse/infinite-giphy/pull/1
