### ISSUE TITLE
Part One

### ISSUE THREAD

**Issue by jenpen** [ga-dc/thanksgiving-homework#56]
https://github.com/jenpen/spotify-me

Completeness: 1
Comfort: 2

Admittedly didn't get to this over the holiday. I'm having trouble figuring out where my keys should be stored so that I can keep that information off github (I get that with Rails, I could use the figaro gem). Reviewing the lecture didn't refresh so will look into it separately.

**Comment by andrewsunglaekim** [comment]
When we talk about obfuscating keys on the client side, it's literally impossible. What you have to do is have your server make the call for you. This call should happen in some controller action and then json should be rendered so you can access it on the client side.
