### ISSUE TITLE
Thanksgiving Homework

### ISSUE THREAD

**Issue by mpopv** [ga-dc/thanksgiving-homework#57]
# Part 1

Comfort: 4
Completeness: 4

https://github.com/mpopv/movie-browser

I liked this one a lot. The most difficult part was getting the titles to properly call and append to the dropdown menu. Did a lot of refactoring based on input from others. But it works almost perfectly and looks pretty, although it's not very responsive, so there's more to do. 
# Part 2

Comfort: 3
Completeness: 3
### How is Express related to the MEAN stack?

It's the E in MEAN (Mongo, Express, Angular, Node). It is a server-side web app framework built in JavaScript for node.js.
### How does Express differ from a framework like Sinatra?

Express is built in/for JavaScript, while Sinatra is built in/for Ruby.
### How would you choose one over the other when starting a new project?

Express definitely seems more powerful when dealing with large, complicated apps, so it might be a better choice when starting a huge, multifaceted project. This might not be what the question is getting at but it might be important to consider which language the programmer(s) in question are best at writing, as well as what kind of support (i.e. gems / modules) is available for the tasks you are trying to accomplish so you're not reinventing a wheel that's already prefabricated in the other language.
### What big picture questions do you have?

Lots. The tutorial was a little confusing. It probably didn't help that last week seemed to go by in a blur and I was sick for a big chunk of it, so I need to review & practice more.

*updated because i'm bad at markdown

**Comment by mattscilipoti** [comment]
Glad you like it.
