### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by tomiteo** [ga-dc/thanksgiving-homework#58]
How is Express related to the MEAN stack?
Express is the E in MEAN. I believe Express handles the MVC functionality of a web application.

How does Express differ from a framework like Sinatra?
It seems like with Sinatra there were many conventions you had to follow which often made things, easier. Whereas, with Express, one must write out all intended functionality longhand.
Also, Sinatra had access to active record, whereas we haven't learned anything comparable for Express yet.

How would you choose one over the other when starting a new project?
It seems like if you want to get up and running quickly and just get your app working, Sinatra is the way to go. But if you want to control everything about your application, then Express might be for you.

What big picture questions do you have?
Why did we learn Sinatra/Rails before Express/Node?

and, in the following pattern--is the $.ajax function _returning_ the data that gets passed into the done function? how else could one access it?

``` js
  $.ajax({
    url: url,
    method: "get"
  }).done(function(data) {
    displayResults(data);
  });
```

**Comment by jshawl** [comment]
> Why did we learn Sinatra/Rails before Express/Node?

To sandwich! We've found the market demands JS knowledge more than ruby at least in DC. We want to sandwhich ruby in the middle to teach the fundamental concepts, but leave people feeling stronger w/ js overall.

> is the $.ajax function returning the data that gets passed into the done function? how else could one access it?

Yes! Well, technically `$.ajax` returns a promise - and it's all callbacks under the hood. Here's some code I wrote that supports both callbacks and promises - https://github.com/jshawl/httpster/blob/master/httpster.js#L9

:+1:
