### ISSUE TITLE
Andre Shonubi Thanksgiving hw - Spotify.me

### ISSUE THREAD

**Issue by codedre** [ga-dc/thanksgiving-homework#6]
completeness: 5 bonus: 4.5 (timeboxed)
comfort: 5

JS is great why did you ever teach me rails lol

https://github.com/codedre/spotify-me/tree/andre_solution

**Comment by Ly900** [comment]
lol Andre

**Comment by codedre** [comment]
Part 2

so this tutorial was very confusing and I really did know what I was supposed to get out of it. I understood what I was typing but it was not clear what context or concepts I could apply this too. I would rather do another tunr with express than that tutorial.

How is Express related to the MEAN stack?

Express is the E in the MEAN stack and is basically a server for running js apps. It acts as a router/controller just like sinatra.

How does Express differ from a framework like Sinatra?

It felt very similar with the difference being languages JS/ruby. Its hard to say which would I choose for a project because I have yet to do anything in express really. I like JS over ruby even with all the helpers so I am excited to learn more. Also it just seems a lot quicker to get things up and running in express.

What big picture questions do you have?

Just want to dive deeper into express just like we did with rails.

**Comment by mattscilipoti** [comment]
:+1: Thanks for your feedback.
