### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by jenpen** [ga-dc/thanksgiving-homework#60]
Reflection: I didn't really get alot out of this tutorial - I felt like I had missed a step going in and went back a few levels (which was a good refresher on JS...). I got practice with the terminal commands, but don't really feel like I have a better understanding of Express that something like building a project would have given me. I've found a few other tutorials that I'll be going through. 

How is Express related to the MEAN stack?
It is the "E" in MEAN. It is what we use for the back-end setup. 

How does Express differ from a framework like Sinatra?
Sinatra felt much faster to set up and gives you the advantage of installing gems. I still haven't figured out the Figaro equivalent for express/JS. 

How would you choose one over the other when starting a new project?
I think it would depend on whether I was more comfortable with Ruby or JS.

What big picture questions do you have?
Not comfortable with this question yet. Feel like I need to build something from scratch in order to figure out my questions.

**Comment by andrewsunglaekim** [comment]
I would recommend building the app i wrote in my blogpost! http://andrewsunglaekim.github.io/A-Not-So-MEAN-Reminder-App/
