### ISSUE TITLE
Murgia Part Two

### ISSUE THREAD

**Issue by murgia** [ga-dc/thanksgiving-homework#61]
How is Express related to the MEAN stack?
Express allows us to use javascript to make JSON queries.

How does Express differ from a framework like Sinatra?
Sinatra uses controllers while express has different dependencies that dictate the convention.

How would you choose one over the other when starting a new project?
It all depends on what you are using.  If you are planning on doing the whole thing in javascript then there are performance benefits and developing benefits to only using one language.

What big picture questions do you have?
Is knowing this stack something thats starting to become more popular? Where does it fit in.

**Comment by andrewsunglaekim** [comment]
the Mean stack is garnering a lot of popularity. Its just another stack that people build entire applications out of.
