### ISSUE TITLE
Part Two

### ISSUE THREAD

**Issue by aoave** [ga-dc/thanksgiving-homework#63]
- Allows us to use javascript to make JSON queries
- Express uses different dependencies that dictate convention where as Sinatra uses controllers
- Depending on what the project calls for I would use whatever is most efficient and performs the best
- I guess that what would be the most practical use in the wild?

**Comment by adambray** [comment]
Hey AO,

I can't find anything for Part 1, do you have anything?

For part 2, here's a summary I gave to Kelly:

The main advantages of JS/Express are that the code runs very fast, and thus scales well to 1000s and 100,000s of users (and more), with few servers.

The main advantages of ruby are: easier to read / write code, better documentation (most of the time),, and more gems / libraries, at the cost of our code running slower.

**Comment by aoave** [comment]
https://github.com/aoave/movie-browser
