### ISSUE TITLE
M. Shofner - Thanksgiving HW

### ISSUE THREAD

**Issue by MarkhamShofner** [ga-dc/thanksgiving-homework#64]
# Part 1

https://github.com/MarkhamShofner/movie-browser
Comfort: 3
Completeness: 1 
I am going to rework through this and the other two exercises. I understand APIs / Ajax in theory, but need some practice.
# Part 2
## How is Express related to the MEAN stack?

The “E” in MEAN (Mongo, Express, Angular, Node). Express is a web framework that allows us to run an rMVC style app, akin to Rails. Receives requests, and returns responses. 
## How does Express differ from a framework like Sinatra?

Express - asynchronous coding (JSON, Ajax), JavaScript as behavioral language.
Sinatra - synchronous, Ruby.  
## How would you choose one over the other when starting a new project?

Express - single page apps, API interactions, asynchronous needs.
Sinatra/Rails - larger databases.
## What big picture questions do you have?

Is there an equivalent resource for Express as the Rails Guides?

**Comment by mattscilipoti** [comment]
We like the Express docs: http://expressjs.com/en/index.html (Use the menu in the upper left corner).
Form John, "Scotch.io has some really nice walkthroughs for express too: https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4"
