### ISSUE TITLE
Becky's Homework 

### ISSUE THREAD

**Issue by beckybeauchamp1** [ga-dc/thanksgiving-homework#9]
PART 1: Infinite-Giphy: 
Comfort_Level: 3/4
Completeness: 4

I feel like there may be a better way to solve this problem and refactor my code. Will come back to this later!
https://github.com/beckybeauchamp1/infinite-giphy

PART 2:

Node.js is an open source platform that provides a runtime environment for developing server side web applications. It uses an event-driven model and asynchronous callbacks. Express is the server side framework written in JavaScript run on Node. 

Overall, I am really excited to learn more about Node and Express, however, I was a little confused at some parts of the ExpressWorks tutorial and hope they will become clearer after this week!  
1.  How is Express related to the MEAN stack?
   The MEAN stack is a JavaScript based stack of technologies used together for building web applications. The four components include MongoDB (a NoSQL database), Express.js, a sever side web application framework, Angular.js, a front end JavaScript framework for the client-side, which all run upon Node.js, a software platform and runtime environment for these technologies. Express specifically provides a framework that allows us to run JavaScript on a server, providing us with additional functionality and methods to use when building web applications. 
2.  How does Express differ from a framework like Sinatra?
   Express is very similar to Sinatra with much fewer conventions and structure than Rails or similar frameworks. Express and Sinatra are considered to be minimal and flexible for developers to decide how to structure their web application and what additional plugins to use. 
3.  How would you choose one over the other when starting a new project?
   I could see advantages to using both, and it would depend on what I was trying to build and for whom. For example, I might would chose Node/Express if I was choosing to build an app which heavily relied on using real time data. Additionally, for example if I was building a game I might chose Node/Express over Rails. However if security was an even greater concern for my application, it appears so far that Rails’s conventions and features allow us to secure our applications very easily. 
4.  What big picture questions do you have?
   I am still a little confused fully about Middleware and would like a deeper understanding of what’s happening big picture when we are calling middleware functions in Express.

**Comment by adambray** [comment]
Hey Becky,

Fantastic answers to the questions on part 2!  I especially thought your answer to Q3 was great.

As for your question on middleware, come grab me at some point this week and we can talk about it if you still have questions. It's easiest to describe in person, with a quick diagram or two.

-Adam
